{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d30a0c1-0aad-40ed-b524-b5b12a5bbe16",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "from Bio import SeqIO\n",
    "from io import StringIO\n",
    "import re\n",
    "import plotly.express as px\n",
    "from Bio.Seq import Seq\n",
    "\n",
    "# Title and description\n",
    "st.title('Advanced DNA Promoter Prediction and Non-B DNA Motif Analysis')\n",
    "st.write('Upload multiple FASTA files to analyze DNA motifs, predict promoter regions, and visualize results.')\n",
    "\n",
    "# Displaying image on the right side\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <div style=\"display: flex; justify-content: flex-end; align-items: center;\">\n",
    "        <img src=\"images/k.png\" alt=\"Advanced DNA Analysis\" style=\"width: 300px; height: auto; border-radius: 10px;\">\n",
    "    </div>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "# Uploading files\n",
    "uploaded_files = st.file_uploader(\"Upload FASTA Files\", type=['fasta'], accept_multiple_files=True)\n",
    "\n",
    "# Dictionary of motifs\n",
    "motifs = {\n",
    "    \"Slipped DNA\": re.compile(r'([ATGC]{2,6})\\1{1,}'),\n",
    "    \"Z-DNA\": re.compile(r'(CG){6,}'),\n",
    "    \"Short Tandem Repeat\": re.compile(r'([ATGC]{2,6})\\1{2,}'),\n",
    "    \"I-Motif\": re.compile(r'((C[A,T]C){3,})'),\n",
    "    \"R-Loop\": re.compile(r'(A{4,}[CG]{2,}A{4,})'),\n",
    "    \"Cruciform\": re.compile(r'([ATGC]{4,})\\1{2,}'),\n",
    "    \"G-Quadruplex\": re.compile(r'(G{3,}[ATGC]{1,5}G{3,}[ATGC]{1,5}G{3,}[ATGC]{1,5}G{3,})'),\n",
    "    \"Hairpin\": re.compile(r'([ATGC]{4,})\\1{1,}'),\n",
    "    \"Triplex\": re.compile(r'(A{3,}[ATGC]{1,}A{3,})'),\n",
    "    \"H-DNA\": re.compile(r'([AG]{4,}[CT]{4,}[AG]{4,})'),\n",
    "    \"Triplex-forming oligonucleotide (TFO)\": re.compile(r'([GATC]{6,}[AG]{4,}[CT]{4,})')\n",
    "}\n",
    "\n",
    "# Function to find inverted repeats\n",
    "def find_inverted_repeats(sequence):\n",
    "    inverted_repeat_results = []\n",
    "    pattern = r'([ATGC]{3,})[ATGC]{0,10}([ATGC]{3,})'\n",
    "    for match in re.finditer(pattern, str(sequence)):\n",
    "        part1 = match.group(1)\n",
    "        part2 = match.group(2)[::-1]  # Reverse complement\n",
    "        if part1 == part2:\n",
    "            inverted_repeat_results.append({\n",
    "                \"Motif\": \"Inverted Repeat\",\n",
    "                \"Start\": match.start() + 1,\n",
    "                \"End\": match.end(),\n",
    "                \"Matched Sequence\": sequence[match.start():match.end()]\n",
    "            })\n",
    "    return inverted_repeat_results\n",
    "\n",
    "# Main logic\n",
    "if uploaded_files:\n",
    "    results = []\n",
    "    for uploaded_file in uploaded_files:\n",
    "        fasta_content = uploaded_file.read().decode('utf-8')\n",
    "        sequences = SeqIO.parse(StringIO(fasta_content), 'fasta')\n",
    "        for record in sequences:\n",
    "            sequence = str(record.seq)\n",
    "            sequence_results = []\n",
    "            # Analyze motifs\n",
    "            for motif_name, motif_pattern in motifs.items():\n",
    "                for match in re.finditer(motif_pattern, sequence):\n",
    "                    sequence_results.append({\n",
    "                        \"Motif\": motif_name,\n",
    "                        \"Start\": match.start() + 1,\n",
    "                        \"End\": match.end(),\n",
    "                        \"Matched Sequence\": match.group()\n",
    "                    })\n",
    "            # Analyze inverted repeats\n",
    "            sequence_results.extend(find_inverted_repeats(sequence))\n",
    "            # Add results\n",
    "            for result in sequence_results:\n",
    "                result.update({\"Sequence ID\": record.id})\n",
    "                results.append(result)\n",
    "    \n",
    "    # Create a DataFrame from results\n",
    "    results_df = pd.DataFrame(results)\n",
    "    st.write(\"Results Overview:\")\n",
    "    st.dataframe(results_df)\n",
    "\n",
    "    # Visualization\n",
    "    if not results_df.empty:\n",
    "        motif_counts = results_df['Motif'].value_counts().reset_index()\n",
    "        motif_counts.columns = ['Motif', 'Count']\n",
    "        st.write(\"Motif Occurrence Visualization:\")\n",
    "        fig = px.bar(motif_counts, x='Motif', y='Count', title='Motif Occurrence Count', labels={'Count': 'Number of Occurrences'})\n",
    "        st.plotly_chart(fig)\n",
    "\n",
    "    # Download results\n",
    "    csv = results_df.to_csv(index=False)\n",
    "    st.download_button(\n",
    "        label=\"Download Results as CSV\",\n",
    "        data=csv,\n",
    "        file_name=\"dna_motif_analysis_results.csv\",\n",
    "        mime=\"text/csv\"\n",
    "    )\n",
    "else:\n",
    "    st.info(\"Please upload FASTA files to proceed.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
